set -g prefix C-Space
set -g mode-keys vi
bind x copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind C-b
bind C-Space send-prefix

bind l choose-window
bind w kill-pane

# navigate windows with [ and ]
bind [ previous-window
bind ] next-window

# navigate panes with arrow keys
bind Up    select-pane -U
bind Left  select-pane -L
bind Down  select-pane -D
bind Right select-pane -R

# status bar
set -g status on
set -g status-position bottom
set -g status-left "#[fg=green]#S "
set -g status-right "%H:%M"
set -g status-style "bg=#191724,fg=#e0def4"
set -g window-status-current-style "fg=#ea9d34,bold"
